{% set name = "django-picklefield" %}
{% set version = "3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-picklefield-{{ version }}.tar.gz
  sha256: 4e76dd20f2e95ffdaf18d641226ccecc169ff0473b0d6bec746f3ab97c26b8cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - django
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=4.2
    # - tox 
    # - Django >=4.2

test:
  imports:
    - picklefield
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/gintas/django-picklefield
  summary: Pickled object field for Django
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mxr-conda
